Fix cluster node started check
opensearch-project/opensearch-net-abstractions pull request #18
Opened 2022-08-23 19:40 UTC by Yury-Fridlyand

Signed-off-by: Yury-Fridlyand <yuryf@bitquilltech.com>

Abstractions runs OpenSearch and track the health and status of the each cluster node by reading `stdout`/`stderr`. Being subscribed to the wrong lines the library decided that node didn't start while it is actually started.

### Description
Fix validation for OpenSearch node start.

### Issues Resolved
Integration test failure on some versions (1.3.x with security).
I predict also failures with security plugin deactivated or uninstalled.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-24 01:44 UTC, Yury-Fridlyand commented
[See test results](https://github.com/Bit-Quill/opensearch-net/actions?query=branch%3Adev-os-2.0-integ-abstractions)
Branch [dev-os-2.0-integ-abstractions](https://github.com/Bit-Quill/opensearch-net/tree/dev-os-2.0-integ-abstractions) based on [dev-os-2.0-integ](https://github.com/Bit-Quill/opensearch-net/tree/dev-os-2.0-integ), see [PR #51](https://github.com/opensearch-project/opensearch-net/pull/51/).
![image](https://user-images.githubusercontent.com/88679692/186298995-f9360844-9976-4cd0-b077-e4d9406f55f6.png)

2022-08-25 17:25 UTC, joshuali925 approved these changes

2022-08-25 20:00 UTC, MaxKsyunz requested changes

2022-08-25 20:00 UTC, MaxKsyunz commented on src/OpenSearch.OpenSearch.Managed/ConsoleWriters/LineOutParser.cs
> -			var inNodeSection = _securityPluginRegex.IsMatch(section);
Can you remove `_securityPluginRegex`? It's not used any more.

Looks like you'll be able to remove `securityPluginName` parameter from `LineOutParser` as well.

2022-08-26 15:29 UTC, MitchellGale-BitQuill approved these changes

2022-08-26 17:04 UTC, MaxKsyunz approved these changes
_securityPluginRegex comment is minor and can be done later.

2022-08-29 20:51 UTC, wbeckler approved these changes

2022-08-29 20:52 UTC, merged